### ISSUE TITLE
使用此框架的组件似乎必须要求在项目内依赖 vue-router

### ISSUE THREAD

**Issue by ruibaby** [TuSimple/naive-ui#159]
### TuSimple/naive-ui version (版本)
2.11.12

### Vue version (Vue 版本)
3.1.1

### Browser and its version (浏览器及其版本)
91.0.4472.77

### System and its version (系统及其版本)
Linux

### Node version (Node 版本)
v14.16.1

### Reappearance link (重现链接)
https://codesandbox.io/s/eloquent-hermann-918wn?file=/src/components/HelloWorld.vue

### Reappearance steps (重现步骤)
安装 naive-ui 后在组件内引用任意组件，参考文档：https://www.naiveui.com/zh-CN/light/docs/usage-sfc 

### Expected results (期望的结果)
无需引入 Vue Router。

### Actual results (实际的结果)
无法正常启动，提示需要依赖 vue-router。

使用 Vue CLI ：

```bash
This dependency was not found:

* vue-router in ./node_modules/naive-ui/es/_deprecated/service-layout/src/ServiceLayout.js, ./node_modules/naive-ui/es/typography/src/a.js

To install it, you can run: npm install --save vue-router

```

使用 Vite：

```bash
yarn run v1.22.10
warning package.json: No license field
warning ../package.json: No license field
$ vite
Pre-bundling dependencies:
  vue
  naive-ui
(this will be run only when your dependencies or config have changed)
 > node_modules/naive-ui/es/_deprecated/service-layout/src/ServiceLayout.js:3:36: error: Could not resolve "vue-router" (mark it as external to exclude it from the bundle)
    3 │ import { useRoute, useRouter } from 'vue-router';
      ╵                                     ~~~~~~~~~~~~                                                                  
                                                                                                                          
 > node_modules/naive-ui/es/typography/src/a.js:2:27: error: Could not resolve "vue-router" (mark it as external to exclude it from the bundle)
    2 │ import { RouterLink } from 'vue-router';
      ╵                            ~~~~~~~~~~~~                                                                           
                                                                                                                          
error when starting dev server:
Error: Build failed with 2 errors:
node_modules/naive-ui/es/_deprecated/service-layout/src/ServiceLayout.js:3:36: error: Could not resolve "vue-router" (mark it as external to exclude it from the bundle)                                                                            
node_modules/naive-ui/es/typography/src/a.js:2:27: error: Could not resolve "vue-router" (mark it as external to exclude it from the bundle)                                                                                                        
    at failureErrorWithLog (/home/ryanwang/workspace/playground/native-ui-demo/node_modules/esbuild/lib/main.js:1449:15)
    at /home/ryanwang/workspace/playground/native-ui-demo/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/home/ryanwang/workspace/playground/native-ui-demo/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/home/ryanwang/workspace/playground/native-ui-demo/node_modules/esbuild/lib/main.js:1129:7)
    at /home/ryanwang/workspace/playground/native-ui-demo/node_modules/esbuild/lib/main.js:1236:14
    at /home/ryanwang/workspace/playground/native-ui-demo/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/home/ryanwang/workspace/playground/native-ui-demo/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/home/ryanwang/workspace/playground/native-ui-demo/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Remarks (补充说明)

无

**Comment by 07akioni** [comment]
`a` component in naive-ui depends on vue-router. `vue-router` is a peerDep of naive-ui. You need to install it.

**Comment by 07akioni** [comment]
I'll try to remove the dep.

**Comment by 07akioni** [comment]
resolved in #162
