### ISSUE TITLE
SSR Date Picker drop document is not defined error

### ISSUE THREAD

**Issue by pitama** [TuSimple/naive-ui#2322]
### TuSimple/naive-ui version (版本)
2.24.7

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
Chrome 97.0.4692.99 

### System and its version (系统及其版本)
MacOs 12.1

### Reappearance link (重现链接)
https://gitlab.com/pitama99/naiveui-ssr/-/tree/master

### Reappearance steps (重现步骤)
After when is install the component library to my ssr demo it's works. But when I add the datepicker to my Home page, after restart it's drop an error:
```
ReferenceError: document is not defined
    at Object.queryElement (/Users/pintertamas/Frontside/ssr-vue/node_modules/css-render/lib/utils.js:17:5)
    at Object.mount (/Users/pintertamas/Frontside/ssr-vue/node_modules/css-render/lib/mount.js:62:35)
    at Object.wrappedMount [as mount] (/Users/pintertamas/Frontside/ssr-vue/node_modules/css-render/lib/c.js:14:35)
    at setup (/Users/pintertamas/Frontside/ssr-vue/node_modules/vueuc/lib/binder/src/Follower.js:97:15)
    at callWithErrorHandling (/Users/pintertamas/Frontside/ssr-vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/Users/pintertamas/Frontside/ssr-vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6966:29)
    at setupComponent (/Users/pintertamas/Frontside/ssr-vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6922:11)
    at renderComponentVNode (/Users/pintertamas/Frontside/ssr-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
    at renderVNode (/Users/pintertamas/Frontside/ssr-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)
    at renderVNodeChildren (/Users/pintertamas/Frontside/ssr-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:325:9)
```

### Expected results (期望的结果)
Works with ssr

### Actual results (实际的结果)
it's not working

**Comment by Talljack** [comment]
maybe same this https://github.com/07akioni/css-render/issues/564

**Comment by pitama** [comment]
> maybe same this [07akioni/css-render#564](https://github.com/07akioni/css-render/issues/564)

I looked, It can't help me

**Comment by 07akioni** [comment]
I find there's a issue for date picker dropdown panel rendering. You can create an new issue for that. We will try to fix it.

**Comment by pitama** [comment]
@07akioni then your firs tip is not working? Or what you find, it's another issue?

**Comment by fabianwohlfart** [comment]
Hi guys,
I have this problem in Nuxt 3.
Any advice?
